server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  server:
    enable-self-preservation: false
#  instance:
#    lease-renewal-interval-in-seconds: 1
#    lease-expiration-duration-in-seconds: 2
management:
  endpoints:
    web:
      exposure:
        include: "*"